./weightedLogit.py ./input-15 weightedLogit 10
./weightedLogit.py ./input-15 weightedLogit 9
./weightedLogit.py ./input-15 weightedLogit 8
./weightedLogit.py ./input-15 weightedLogit 7
./weightedLogit.py ./input-15 weightedLogit 6
./weightedLogit.py ./input-15 weightedLogit 5
./weightedLogit.py ./input-15 weightedLogit 4
./weightedLogit.py ./input-15 weightedLogit 3
./weightedLogit.py ./input-15 weightedLogit 2
./weightedLogit.py ./input-15 weightedLogit 1
